[pytest]
markers =
    need_review
    new_user_card_ru_subscription_purchase
    old_user_card_ru_subscription_purchase
    new_user_sbp_ru_subscription_purchase
    old_user_sbp_ru_subscription_purchase
    new_user_card_kz_subscription_purchase
    old_user_card_kz_subscription_purchase
